name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main  # Listen for changes on the main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.15'
    
    # Setup pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.10.0

    # Install dependencies
    - name: Install dependencies
      run: pnpm www:install

    # Build for GitHub Pages
    - name: Build VitePress site for GitHub Pages
      run: pnpm www:build
      
    # Add CNAME for GitHub Pages
    - name: Add CNAME for GitHub Pages
      run: echo "kugarocks.github.io" > ./sites/www/.vitepress/dist/CNAME

    # Deploy the contents to gh-pages branch
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./sites/www/.vitepress/dist
        publish_branch: gh-pages

    # Create a separate build for Aliyun Pages
    - name: Create separate directory for Aliyun build
      run: mkdir -p ./sites/www/.vitepress/dist-aliyun
      
    # Build again for Aliyun Pages
    - name: Build VitePress site for Aliyun Pages
      run: |
        # 清除之前的构建缓存，确保干净构建
        rm -rf ./sites/www/.vitepress/.temp
        pnpm www:build
        # 将构建结果复制到阿里云专用目录
        cp -r ./sites/www/.vitepress/dist/* ./sites/www/.vitepress/dist-aliyun/

    # Update CNAME for Aliyun Pages
    - name: Update CNAME for Aliyun Pages
      run: echo "www.kugarocks.com" > ./sites/www/.vitepress/dist-aliyun/CNAME

    # Deploy the contents to al-pages branch
    - name: Deploy to Aliyun Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./sites/www/.vitepress/dist-aliyun
        publish_branch: al-pages

    # Notify Aliyun server to pull code using HTTP webhook
    - name: Notify Aliyun server to pull code
      run: |
        curl -X POST "https://api.kugarocks.com/webhook" \
        -H "Content-Type: application/json" \
        -d '{"action": "git-pull", "repo": "kugarocks.github.io", "branch": "al-pages"}'
