name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main  # Listen for changes on the main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.15'
    
    # Setup pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.10.0

    # Install dependencies
    - name: Install dependencies
      run: pnpm www:install

    # Build the VitePress site for GitHub Pages
    - name: Build VitePress site for GitHub Pages
      run: pnpm www:build:github

    # Create gh-pages directory if it doesn't exist
    - name: Create gh-pages directory
      run: mkdir -p ./gh-pages

    # Copy build files to gh-pages directory
    - name: Copy build files to gh-pages
      run: cp -r ./sites/www/.vitepress/dist/* ./gh-pages/

    # Add custom domain for GitHub Pages
    - name: Add CNAME file for GitHub Pages
      run: echo "kugarocks.github.io" > ./gh-pages/CNAME

    # Deploy the contents of the gh-pages directory
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages

    # Build the VitePress site for Aliyun Pages
    - name: Build VitePress site for Aliyun
      run: pnpm www:build:aliyun

    # Create al-pages directory if it doesn't exist
    - name: Create al-pages directory
      run: mkdir -p ./al-pages

    # Copy build files to al-pages directory
    - name: Copy build files to al-pages
      run: cp -r ./sites/www/.vitepress/dist/* ./al-pages/

    # Add custom domain for Aliyun Pages
    - name: Add CNAME file for Aliyun Pages
      run: echo "www.kugarocks.com" > ./al-pages/CNAME

    # Deploy the contents of the al-pages directory
    - name: Deploy to Aliyun Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./al-pages
        publish_branch: al-pages

    # Notify Aliyun server to pull code using HTTP webhook
    - name: Notify Aliyun server to pull code
      run: |
        curl -X POST "https://api.kugarocks.com/webhook" \
        -H "Content-Type: application/json" \
        -d '{"action": "git-pull", "repo": "kugarocks.github.io", "branch": "al-pages"}'
